ApiGateway:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn:
              Fn::Sub: arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPool}
            Identity:
              Header: Authorization
      DefinitionBody:
        swagger: 2
        info:
          title:
            Ref: 'AWS::StackName'
        paths: {}